osx_image: xcode8.3
os: osx

language: c

## all packages after rpm is required for rpm

before_install:
  - brew install p7zip --force-bottle

script:
  - ln -sf $PWD/github-release /usr/local/bin/github-release

  # linux-tools
  - mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
  - homebrew/bin/brew install gnu-tar xz rpm --force-bottle
  - cd homebrew

  - 7za a -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on -xr'!man' -xr'!doc' -xr'!include' -xr'!CHANGES' /tmp/linux-tools-mac-10.12.7z bin Cellar lib opt

  - CHECKSUM=$(shasum -a 512 /tmp/linux-tools-mac-10.12.7z | xxd -r -p | base64)
  - 'github-release electron-userland/electron-builder-binaries linux-tools-mac-10.12 master "Sha512: $CHECKSUM" /tmp/linux-tools-mac-10.12.7z'