#!/usr/bin/env bash
set -ex

# This script compresses the artifacts generated by the build process.
# This script is super verbose, but it's meant to be an interim step as we convert the release process to be fully automated by Github Actions

BASE_DIR=$(cd "$(dirname "$0")" && pwd)
ARTIFACTS_DIR=$BASE_DIR/artifacts
rm -rf "$ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"

touch $ARTIFACTS_DIR/checksums.txt


# ztsd
NAME="zstd"
VERSION="v1.5.5"
for FOLDER_NAME in "linux-x64" "mac" "win-ia32" "win-x64" "win-x64" 
do
    ARCHIVE_NAME="$NAME-$VERSION-$FOLDER_NAME.7z"
    $BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/zstd/$FOLDER_NAME"/*
    CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
    echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"
done

# appimage
NAME="appimage"
VERSION="13.0.1"
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/AppImage"/*
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"

# nsis
NAME="nsis"
VERSION="3.0.5.0"
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/$NAME"/*
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"

# winCodeSign
NAME="winCodeSign"
VERSION="2.6.0"
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/$NAME"/*
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"

# nsis-resources
NAME="nsis-resources"
VERSION="3.4.1"
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/$NAME"/*
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"

# wine-4.0.1-mac
# needs compilation on macOS runner, for now we just copy previous distributable as interim solution
NAME="wine"
VERSION=4.0.1-mac
ARCHIVE_NAME="$NAME-$VERSION.7z"
cp -a $BASE_DIR/$NAME/$ARCHIVE_NAME "$ARTIFACTS_DIR/$ARCHIVE_NAME"
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"

# snap-template-4.0
# needs compilation on on GH runner, for now we just copy previous distributable as interim solution
NAME="snap-template"
VERSION=4.0
cp -a $BASE_DIR/$NAME/* "$ARTIFACTS_DIR/"
ARCHIVE_NAME="snap-template-electron-4.0.tar.7z"
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"
ARCHIVE_NAME="snap-template-electron-4.0-1-armhf.tar.7z"
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"
ARCHIVE_NAME="snap-template-electron-4.0-2-amd64.tar.7z"
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"

# Squirrel.Windows
NAME="Squirrel.Windows"
VERSION=1.9.0
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/$NAME"/*
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"

# nsis-resources
NAME="nsis-resources"
VERSION=3.4.1
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/$NAME"/*
CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"