#!/usr/bin/env bash
set -ex

# This script compresses the artifacts generated by the build process.
# This script is super verbose, but it's meant to be an interim step as we convert the release process to be fully automated by Github Actions

BASE_DIR=$(cd "$(dirname "$0")" && pwd)
ARTIFACTS_DIR=$BASE_DIR/artifacts
rm -rf "$ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"

touch $ARTIFACTS_DIR/checksums.txt

hashArtifact()
{
    ARCHIVE_NAME=$1
    CHECKSUM=$(shasum -a 512 "$ARTIFACTS_DIR/$ARCHIVE_NAME" | xxd -r -p | base64)
    echo "$ARCHIVE_NAME: $CHECKSUM" >> "$ARTIFACTS_DIR/checksums.txt"
}

downloadArtifact()
{
    NAME=$1
    VERSION=$2
    RELEASE_NAME="$NAME-$VERSION"
    ARCHIVE_NAME="$NAME-$VERSION.7z"
    curl -L https://github.com/electron-userland/electron-builder-binaries/releases/download/$RELEASE_NAME/$ARCHIVE_NAME > "$ARTIFACTS_DIR/$ARCHIVE_NAME"
    hashArtifact "$ARCHIVE_NAME"
}

compressArtifact()
{
    NAME=$1
    VERSION=$2
    ARCHIVE_NAME="$NAME-$VERSION.7z"
    $BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/$NAME"/*
    hashArtifact "$ARCHIVE_NAME"
}

# ztsd
NAME="zstd"
VERSION="v1.5.5"
for FOLDER_NAME in "linux-x64" "mac" "win-ia32" "win-x64" "win-x64" 
do
    ARCHIVE_NAME="$NAME-$VERSION-$FOLDER_NAME.7z"
    $BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/zstd/$FOLDER_NAME"/*
    hashArtifact "$ARCHIVE_NAME"
done

# appimage
NAME="appimage"
VERSION="13.0.1"
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -mx=9 -mfb=64 "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/AppImage"/*
hashArtifact "$ARCHIVE_NAME"

# nsis
NAME="nsis"
VERSION="3.0.5.0"
compressArtifact "$NAME" "$VERSION"

# winCodeSign
NAME="winCodeSign"
VERSION="2.6.0"
compressArtifact "$NAME" "$VERSION"

# nsis-resources
NAME="nsis-resources"
VERSION="3.4.1"
compressArtifact "$NAME" "$VERSION"

# wine-4.0.1-mac
NAME="wine"
VERSION=4.0.1-mac
downloadArtifact "$NAME" "$VERSION"

# snap-template-4.0
RELEASE_NAME="snap-template-4.0"
ARCHIVE_NAME="snap-template-electron-4.0.tar.7z"
curl -L https://github.com/electron-userland/electron-builder-binaries/releases/download/$RELEASE_NAME/$ARCHIVE_NAME > "$ARTIFACTS_DIR/$ARCHIVE_NAME"
hashArtifact "$ARCHIVE_NAME"
RELEASE_NAME="snap-template-4.0-1"
ARCHIVE_NAME="snap-template-electron-4.0-1-armhf.tar.7z"
curl -L https://github.com/electron-userland/electron-builder-binaries/releases/download/$RELEASE_NAME/$ARCHIVE_NAME > "$ARTIFACTS_DIR/$ARCHIVE_NAME"
ARCHIVE_NAME="snap-template-electron-4.0-1-amd64.tar.7z"
curl -L https://github.com/electron-userland/electron-builder-binaries/releases/download/$RELEASE_NAME/$ARCHIVE_NAME > "$ARTIFACTS_DIR/$ARCHIVE_NAME"
RELEASE_NAME="snap-template-4.0-2"
ARCHIVE_NAME="snap-template-electron-4.0-2-amd64.tar.7z"
curl -L https://github.com/electron-userland/electron-builder-binaries/releases/download/$RELEASE_NAME/$ARCHIVE_NAME > "$ARTIFACTS_DIR/$ARCHIVE_NAME"
hashArtifact "$ARCHIVE_NAME"

# Squirrel.Windows
NAME="Squirrel.Windows"
VERSION=1.9.0
compressArtifact "$NAME" "$VERSION"

# nsis-resources
NAME="nsis-resources"
VERSION=3.4.1
ARCHIVE_NAME="$NAME-$VERSION.7z"
$BASE_DIR/7za a -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on "$ARTIFACTS_DIR/$ARCHIVE_NAME" "$BASE_DIR/$NAME"/*
hashArtifact "$ARCHIVE_NAME"

# linux-tools-mac
NAME="linux-tools-mac"
VERSION=10.12.4
downloadArtifact "$NAME" "$VERSION"

# wix
NAME="wix"
VERSION=4.0.0.5512.2
compressArtifact "$NAME" "$VERSION"

# ran
NAME="ran"
VERSION=0.1.3
downloadArtifact "$NAME" "$VERSION"

# fpm
for FOLDER_NAME in "2.3.1-linux-x86_64" "2.3.1-linux-x86" "20150715-2.2.2-mac"
do
    NAME="fpm"
    VERSION="1.9.3"
    downloadArtifact "$NAME-$VERSION" "$FOLDER_NAME"
done

sort "$ARTIFACTS_DIR/checksums.txt" -o "$ARTIFACTS_DIR/checksums.txt"
echo "Artifacts compressed and checksums generated in $ARTIFACTS_DIR"