name: Build artifacts

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      artifactUrl:
        value: ${{ jobs.combine.outputs.artifactUrl }}
      artifactId:
        value: ${{ jobs.combine.outputs.artifactId }}

permissions:
  contents: read

jobs:
  fpm:
    uses: ./.github/workflows/build-fpm.yml

  squirrel:
    uses: ./.github/workflows/build-squirrel.yml

  combine:
    runs-on: macos-latest
    needs: [fpm, squirrel]
    outputs:
      artifactUrl: ${{ steps.upload.outputs.artifact-url }}
      artifactId: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pnpm/action-setup@v4
        with: { version: 9.4.0 }
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - uses: actions/download-artifact@v4
        with:
          path: out
          merge-multiple: true
      - run: tree ./out
      - run: sh ./scripts/compress-artifacts.sh
      - run: |
          pnpm i --frozen-lockfile
          tree ./artifacts-staging
          DRY_RUN=true node ./scripts/changeset-version.js
      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-staging
          path: artifacts-staging
          if-no-files-found: error
          retention-days: 1
