name: Build Wine

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: wine-${{ github.ref }}-${{ github.run_id }}
  cancel-in-progress: true # for the love of all that is holy, cancel in progress runs on new pushes. linux builds take forever
    
jobs:
  mac:
    runs-on: macos-15
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build for macOS
        run: bash ./build.sh
        shell: bash
        working-directory: ./packages/wine

      - name: Upload wine artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: wine-macos
          path: packages/wine/out/*.tar.xz
          if-no-files-found: error
          retention-days: 1
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # holy moly docker builds take forever
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build for Linux
        run: bash ./build.sh
        shell: bash
        working-directory: ./packages/wine

      - name: Upload wine artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: wine-linux
          path: packages/wine/out/*.tar.xz
          if-no-files-found: error
          retention-days: 1

  combine:
    runs-on: ubuntu-latest
    needs: [mac, linux]
    steps:
      - name: Download wine artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          pattern: wine-*
          merge-multiple: true
          path: staging/wine/

      - name: Upload combined wine artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: wine
          path: staging/
          if-no-files-found: error
          retention-days: 1

      - name: Delete interim artifacts
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b
        with:
          name: |
            wine-macos
            wine-linux
