name: Build Icons Toolset

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build icons toolset
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Enable Corepack for pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: "22"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and test
        run: bash ./build.sh --target all
        shell: bash
        working-directory: ./packages/icons

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: icons-bundle
          path: packages/icons/out/**/*.tar.gz
          if-no-files-found: error
          retention-days: 1
