name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # to create release (changesets/action)
  pull-requests: write # to create pull request (changesets/action)

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yaml

  release:
    runs-on: macos-latest
    needs: build-artifacts
    timeout-minutes: 15
    steps:
      - name: Fetch artifact
        id: artifact-url
        env:
          ARTIFACT_URL: ${{ needs.build-artifacts.outputs.artifactUrl }}
          ARTIFACT_ID: ${{ needs.build-artifacts.outputs.artifactId }}
        run: |
          echo "Artifact URL is: $ARTIFACT_URL"
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> $GITHUB_ENV
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ needs.build-artifacts.outputs.artifactId }}
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Checkout code repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      
      - name: Create versions PR & prepare publish
        id: changesets
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1.4.1
        with:
          version: pnpm ci:version
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}